server:
  name: "knights-login"
  address: "0.0.0.0"
  port: 9002
  service_type: "login"

center:
  address: "localhost:9001"

login:
  address: "0.0.0.0"
  token_expire: 3600

database:
  driver: "mysql"
  host: "localhost"
  port: 3306
  username: "root"
  password: "password"
  database: "knights"

redis:
  address: "localhost:6379"
  password: ""
  db: 0
